print("Selamat datang di permainan Mad Libs, masukkan kata sesuai keterangan yang diminta")
nama = input("Nama: ").upper()
emosi = input("Emosi: ").upper()
tempat = input("Tempat: ").upper()
benda = input("Benda: ").upper()
konsumsi = input("Konsumsi (makanan/minuman): ").upper()
alat = input("Alat: ").upper()
hewan = input("Hewan: ").upper()
sifat1 = input("Kata sifat: ").upper()
kataKerja = input("Kata kerja: ").upper()
sesuatu = input("Sesuatu: ").upper()
sifat2 = input("Kata sifat 2: ").upper()
aktivitas = input("Aktivitas: ").upper()
sifat3 = input("Kata sifat 3: ").upper()
print(f"Pada suatu pagi, {nama} bangun dengan penuh {emosi} karena hari ini adalah hari istimewa. Ia merencanakan untuk pergi ke {tempat} dan menemukan {benda}. Sebelum berangkat, ia membawa {konsumsi} dan {alat} kesayangannya.")
print(f"Setibanya di {tempat}, ia melihat {hewan} yang {sifat1}. Hewan itu meminta bantuan untuk {kataKerja}. {nama} tidak ragu dan segera {kataKerja} bersama {hewan}. Dalam perjalanan, mereka menemukan {sesuatu} yang sangat {sifat2}.")
print(f"Mereka pun merayakan penemuan itu dengan {aktivitas}, dan {nama} merasa sangat {sifat3} karena hari itu menjadi pengalaman yang tak terlupakan. Saat matahari terbenam, ia pulang dengan {sesuatu} dan cerita menarik untuk dibagikan kepada teman-temannya.")